[[domain]]
  id = "WZ2jX47tV5DxFYMo"
  password = "aT3B9r1kcj8X0lgg"
  hostname = "remote.pocketfriends.chat"
  old_ip = ""

[[domain]]
  id = "O9HXTYgVGXaYs5fD"
  password = "HJzf7qE3CPeh8flU"
  hostname = "pocketfriends.chat"
  old_ip = ""
